spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring-boot-env?useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#  redis:
#    host: 127.0.0.1
#    port: 6379
  session:
    store-type: redis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true  # 配置延迟加载选项 add 202201051510
        format_sql: true

#logging:
#  level:
#    root: info
#    liuyang: debug
    #liuyang: trace
#    liuyang.testmbp.service: trace
#  pattern:
#    console: '%p%m%n' # 只关注SQL语句

#mybatis-plus:
#  mapper-locations: classpath*:liuyang/testmbp/mapper/mapping/*.xml
  # Maven多模块项目的扫描路径需要以classpath*开头(即加载多个jar包下的XML)
  # 实测如下配置也可：
  # mapper-locations: classpath:liuyang/testmbp/mapper/mapping/*.xml
  #global-config:
  #  db-config:
  #    id-type: uuid