spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.42.129:3306/spring-boot-env?useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/spring-boot-env?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    #host: 192.168.42.129
    host: localhost
    port: 6379
  thymeleaf:
    cache=false: false